import solaraFlag from "@/assets/flags/solara.webp";

export interface Country {
  name: string;
  code: string;
  /** Custom flag URL override (for fictional countries) */
  customFlag?: string;
}

export const COUNTRIES_DATA: Country[] = [
  { name: "Afeganistão", code: "af" },
  { name: "África do Sul", code: "za" },
  { name: "Albânia", code: "al" },
  { name: "Alemanha", code: "de" },
  { name: "Andorra", code: "ad" },
  { name: "Angola", code: "ao" },
  { name: "Antígua e Barbuda", code: "ag" },
  { name: "Arábia Saudita", code: "sa" },
  { name: "Argélia", code: "dz" },
  { name: "Argentina", code: "ar" },
  { name: "Armênia", code: "am" },
  { name: "Austrália", code: "au" },
  { name: "Áustria", code: "at" },
  { name: "Azerbaijão", code: "az" },
  { name: "Bahamas", code: "bs" },
  { name: "Bahrein", code: "bh" },
  { name: "Bangladesh", code: "bd" },
  { name: "Barbados", code: "bb" },
  { name: "Bélgica", code: "be" },
  { name: "Belize", code: "bz" },
  { name: "Benin", code: "bj" },
  { name: "Bielorrússia", code: "by" },
  { name: "Bolívia", code: "bo" },
  { name: "Bósnia e Herzegovina", code: "ba" },
  { name: "Botsuana", code: "bw" },
  { name: "Brasil", code: "br" },
  { name: "Brunei", code: "bn" },
  { name: "Bulgária", code: "bg" },
  { name: "Burkina Faso", code: "bf" },
  { name: "Burundi", code: "bi" },
  { name: "Butão", code: "bt" },
  { name: "Cabo Verde", code: "cv" },
  { name: "Camarões", code: "cm" },
  { name: "Camboja", code: "kh" },
  { name: "Canadá", code: "ca" },
  { name: "Catar", code: "qa" },
  { name: "Cazaquistão", code: "kz" },
  { name: "Chade", code: "td" },
  { name: "Chile", code: "cl" },
  { name: "China", code: "cn" },
  { name: "Chipre", code: "cy" },
  { name: "Colômbia", code: "co" },
  { name: "Comores", code: "km" },
  { name: "Congo", code: "cg" },
  { name: "Coreia do Norte", code: "kp" },
  { name: "Coreia do Sul", code: "kr" },
  { name: "Costa do Marfim", code: "ci" },
  { name: "Costa Rica", code: "cr" },
  { name: "Croácia", code: "hr" },
  { name: "Cuba", code: "cu" },
  { name: "Curaçao", code: "cw" },
  { name: "Dinamarca", code: "dk" },
  { name: "Djibuti", code: "dj" },
  { name: "Dominica", code: "dm" },
  { name: "Egito", code: "eg" },
  { name: "El Salvador", code: "sv" },
  { name: "Emirados Árabes Unidos", code: "ae" },
  { name: "Equador", code: "ec" },
  { name: "Eritreia", code: "er" },
  { name: "Eslováquia", code: "sk" },
  { name: "Eslovênia", code: "si" },
  { name: "Espanha", code: "es" },
  { name: "Estados Unidos", code: "us" },
  { name: "Estônia", code: "ee" },
  { name: "Eswatini", code: "sz" },
  { name: "Etiópia", code: "et" },
  { name: "Fiji", code: "fj" },
  { name: "Filipinas", code: "ph" },
  { name: "Finlândia", code: "fi" },
  { name: "França", code: "fr" },
  { name: "Gabão", code: "ga" },
  { name: "Gâmbia", code: "gm" },
  { name: "Gana", code: "gh" },
  { name: "Geórgia", code: "ge" },
  { name: "Gibraltar", code: "gi" },
  { name: "Granada", code: "gd" },
  { name: "Grécia", code: "gr" },
  { name: "Guatemala", code: "gt" },
  { name: "Guiana", code: "gy" },
  { name: "Guiné", code: "gn" },
  { name: "Guiné-Bissau", code: "gw" },
  { name: "Guiné Equatorial", code: "gq" },
  { name: "Haiti", code: "ht" },
  { name: "Holanda", code: "nl" },
  { name: "Honduras", code: "hn" },
  { name: "Hungria", code: "hu" },
  { name: "Iêmen", code: "ye" },
  { name: "Ilhas Faroé", code: "fo" },
  { name: "Ilhas Salomão", code: "sb" },
  { name: "Índia", code: "in" },
  { name: "Indonésia", code: "id" },
  { name: "Inglaterra", code: "gb-eng" },
  { name: "Irã", code: "ir" },
  { name: "Iraque", code: "iq" },
  { name: "Irlanda", code: "ie" },
  { name: "Irlanda do Norte", code: "gb-nir" },
  { name: "Islândia", code: "is" },
  { name: "Israel", code: "il" },
  { name: "Itália", code: "it" },
  { name: "Jamaica", code: "jm" },
  { name: "Japão", code: "jp" },
  { name: "Jordânia", code: "jo" },
  { name: "Kosovo", code: "xk" },
  { name: "Kuwait", code: "kw" },
  { name: "Laos", code: "la" },
  { name: "Lesoto", code: "ls" },
  { name: "Letônia", code: "lv" },
  { name: "Líbano", code: "lb" },
  { name: "Libéria", code: "lr" },
  { name: "Líbia", code: "ly" },
  { name: "Liechtenstein", code: "li" },
  { name: "Lituânia", code: "lt" },
  { name: "Luxemburgo", code: "lu" },
  { name: "Macedônia do Norte", code: "mk" },
  { name: "Madagascar", code: "mg" },
  { name: "Malásia", code: "my" },
  { name: "Malawi", code: "mw" },
  { name: "Maldivas", code: "mv" },
  { name: "Mali", code: "ml" },
  { name: "Malta", code: "mt" },
  { name: "Marrocos", code: "ma" },
  { name: "Maurício", code: "mu" },
  { name: "Mauritânia", code: "mr" },
  { name: "México", code: "mx" },
  { name: "Mianmar", code: "mm" },
  { name: "Moçambique", code: "mz" },
  { name: "Moldávia", code: "md" },
  { name: "Mônaco", code: "mc" },
  { name: "Mongólia", code: "mn" },
  { name: "Montenegro", code: "me" },
  { name: "Namíbia", code: "na" },
  { name: "Nepal", code: "np" },
  { name: "Nicarágua", code: "ni" },
  { name: "Níger", code: "ne" },
  { name: "Nigéria", code: "ng" },
  { name: "Noruega", code: "no" },
  { name: "Nova Zelândia", code: "nz" },
  { name: "Omã", code: "om" },
  { name: "País de Gales", code: "gb-wls" },
  { name: "Panamá", code: "pa" },
  { name: "Papua-Nova Guiné", code: "pg" },
  { name: "Paquistão", code: "pk" },
  { name: "Paraguai", code: "py" },
  { name: "Peru", code: "pe" },
  { name: "Polônia", code: "pl" },
  { name: "Portugal", code: "pt" },
  { name: "Quênia", code: "ke" },
  { name: "Quirguistão", code: "kg" },
  { name: "Reino Unido", code: "gb" },
  { name: "República Centro-Africana", code: "cf" },
  { name: "República Democrática do Congo", code: "cd" },
  { name: "República Dominicana", code: "do" },
  { name: "República Tcheca", code: "cz" },
  { name: "Romênia", code: "ro" },
  { name: "Ruanda", code: "rw" },
  { name: "Rússia", code: "ru" },
  { name: "Samoa", code: "ws" },
  { name: "San Marino", code: "sm" },
  { name: "Santa Lúcia", code: "lc" },
  { name: "São Cristóvão e Névis", code: "kn" },
  { name: "São Tomé e Príncipe", code: "st" },
  { name: "São Vicente e Granadinas", code: "vc" },
  { name: "Senegal", code: "sn" },
  { name: "Serra Leoa", code: "sl" },
  { name: "Sérvia", code: "rs" },
  { name: "Singapura", code: "sg" },
  { name: "Síria", code: "sy" },
  { name: "Somália", code: "so" },
  { name: "Solara", code: "solara", customFlag: solaraFlag },
  { name: "Sri Lanka", code: "lk" },
  { name: "Sudão", code: "sd" },
  { name: "Sudão do Sul", code: "ss" },
  { name: "Suécia", code: "se" },
  { name: "Suíça", code: "ch" },
  { name: "Suriname", code: "sr" },
  { name: "Tailândia", code: "th" },
  { name: "Taiwan", code: "tw" },
  { name: "Tajiquistão", code: "tj" },
  { name: "Tanzânia", code: "tz" },
  { name: "Timor-Leste", code: "tl" },
  { name: "Togo", code: "tg" },
  { name: "Tonga", code: "to" },
  { name: "Trinidad e Tobago", code: "tt" },
  { name: "Tunísia", code: "tn" },
  { name: "Turcomenistão", code: "tm" },
  { name: "Turquia", code: "tr" },
  { name: "Tuvalu", code: "tv" },
  { name: "Ucrânia", code: "ua" },
  { name: "Uganda", code: "ug" },
  { name: "Uruguai", code: "uy" },
  { name: "Uzbequistão", code: "uz" },
  { name: "Vanuatu", code: "vu" },
  { name: "Vaticano", code: "va" },
  { name: "Venezuela", code: "ve" },
  { name: "Vietnã", code: "vn" },
  { name: "Zâmbia", code: "zm" },
  { name: "Zimbábue", code: "zw" },
];

/** Legacy array for backward compat */
export const COUNTRIES = COUNTRIES_DATA.map((c) => c.name);

/** Get the flag URL for a country name */
export function getFlagUrl(countryName: string): string | undefined {
  const country = COUNTRIES_DATA.find((c) => c.name === countryName);
  if (!country) return undefined;
  if (country.customFlag) return country.customFlag;
  return `https://flagcdn.com/w80/${country.code}.webp`;
}

/** Get country data by name */
export function getCountryByName(name: string): Country | undefined {
  return COUNTRIES_DATA.find((c) => c.name === name);
}
