// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: "implicit", // PKCE quebra em alguns Android Chrome por problemas no redirect de query params
    storage: (() => {
      const testKey = "__sb_test__";
      try {
        localStorage.setItem(testKey, "1");
        localStorage.removeItem(testKey);
        return localStorage;
      } catch {
        try {
          sessionStorage.setItem(testKey, "1");
          sessionStorage.removeItem(testKey);
          return sessionStorage;
        } catch {
          const mem: Record<string, string> = {};
          return {
            getItem: (k: string) => mem[k] ?? null,
            setItem: (k: string, v: string) => {
              mem[k] = v;
            },
            removeItem: (k: string) => {
              delete mem[k];
            },
          };
        }
      }
    })(),
  },
});
